### ISSUE TITLE
データ取得、検索、処理を担当するStruct

### ISSUE THREAD

**Issue by Walkmana-25** [solufit/anemos-public-api-library#5]
struct: list[anemos internal apiから返ってくるデータ(Anemos.xxxxxx)]

Interfaces:
new: 生成する
get: cacheから取得する
search: 検索

その他、必要に応じて追加してください。

**Comment by sasanqua-dev** [comment]
What is new

**Comment by Walkmana-25** [comment]
https://qiita.com/gold-kou/items/4494f8b69b8fa53d5e93
コンストラクタ的なやつ

**Comment by Walkmana-25** [comment]
細かい仕様はお任せします。

**Comment by Walkmana-25** [comment]
type AnemosGet struct {
supportedType
xxxxxxx: Slicexxxxxxx
yyyyyyy: Sliceyyyyyy
}

func NewAnemosGet () AnemosGet {}

func Getxxxxxxx (*AnemosGet) error {}

xxxxxxxは、anemos.weatherwarningなとのtypeごとにひとつづつ

type xxxxxxxxxxx struct {}

type Slicexxxxxxx struct{
data: []xxxxxxx
}

func Filter(*Slicexxxxxx, FilterOption) Slicexxxxxx {}

type FilterOptiton struct {

}
